language: perl

matrix:
  include:
    - perl: "5.30"
    - perl: "5.22"
    - perl: "5.20"
      dist: trusty
    - perl: "5.16"
      dist: trusty
    - perl: "5.10"
      dist: trusty

before_install:
  - cpanm --installdeps -n -q .
  - cpanm -n -q Devel::Cover

install:
  - true

script:
  - prove -v
  - cover -t +select ^asub +ignore ^t -make 'prove; exit $?; '
